use_frameworks!

target 'CodablePersistenceStore_Example' do
  pod 'CodablePersistenceStore', :path => '../'

  target 'CodablePersistenceStoreTests' do
      pod 'CodablePersistenceStore', :path => '../'
    inherit! :search_paths

    
  end
end
