use_frameworks!
platform :ios, '11.0'


source 'https://github.com/CocoaPods/Specs.git'


target 'CodablePersistenceStore_Example' do
    use_frameworks!
    pod 'CodablePersistenceStore/'
    
  target 'CodablePersistenceStoreTests' do
      pod 'Nimble', '~> 7.0.3'
      pod 'CodablePersistenceStore/'
    inherit! :search_paths

    
  end
end
